"""initial schema

Revision ID: 0001
Revises: 0000
Create Date: 2026-08-29 20:17:40.912912

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "0001"
down_revision = "0000"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contacts",
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("identifier", sa.String(length=64), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=True),
        sa.Column("agency_score", sa.Float(), nullable=False),
        sa.Column("classification", sa.String(length=16), nullable=False),
        sa.Column("distinct_property_count_90d", sa.Integer(), nullable=False),
        sa.Column("human_decision", sa.String(length=16), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("kind", "identifier", name="uq_contact_identity"),
    )
    op.create_table(
        "fx_rates",
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("usd_uzs", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("date"),
    )
    op.create_table(
        "sources",
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("state", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("interval_seconds", sa.Integer(), nullable=False),
        sa.Column("next_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("consecutive_failures", sa.Integer(), nullable=False),
        sa.Column("paused_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("phone_e164", sa.String(length=16), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("locale", sa.String(length=5), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("phone_e164"),
    )
    op.create_table(
        "worker_heartbeat",
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.Column("last_tick_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "crawl_runs",
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("found", sa.Integer(), nullable=False),
        sa.Column("new", sa.Integer(), nullable=False),
        sa.Column("changed", sa.Integer(), nullable=False),
        sa.Column("failed", sa.Integer(), nullable=False),
        sa.Column("removed", sa.Integer(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_crawl_runs_source_id"), "crawl_runs", ["source_id"], unique=False)
    op.create_table(
        "properties",
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("district", sa.String(length=32), nullable=True),
        sa.Column("rooms", sa.Integer(), nullable=True),
        sa.Column("floor", sa.Integer(), nullable=True),
        sa.Column("total_floors", sa.Integer(), nullable=True),
        sa.Column("area_sqm", sa.Float(), nullable=True),
        sa.Column("price_usd_min_minor", sa.BigInteger(), nullable=True),
        sa.Column("probable_owner_contact_id", sa.UUID(), nullable=True),
        sa.Column("owner_confidence", sa.Float(), nullable=True),
        sa.Column("source_removed", sa.Boolean(), nullable=False),
        sa.Column("needs_recheck", sa.Boolean(), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("search_vector", postgresql.TSVECTOR(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["probable_owner_contact_id"], ["contacts.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_properties_district"), "properties", ["district"], unique=False)
    op.create_index(
        "ix_properties_search",
        "properties",
        ["search_vector"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_table(
        "raw_listings",
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("external_id", sa.String(length=120), nullable=False),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("parse_error", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_id", "external_id", name="uq_raw_source_external"),
    )
    op.create_table(
        "listings",
        sa.Column("raw_listing_id", sa.UUID(), nullable=False),
        sa.Column("property_id", sa.UUID(), nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("price_amount_minor", sa.BigInteger(), nullable=True),
        sa.Column("price_currency", sa.String(length=3), nullable=True),
        sa.Column("price_usd_minor", sa.BigInteger(), nullable=True),
        sa.Column("rooms", sa.Integer(), nullable=True),
        sa.Column("area_sqm", sa.Float(), nullable=True),
        sa.Column("floor", sa.Integer(), nullable=True),
        sa.Column("total_floors", sa.Integer(), nullable=True),
        sa.Column("district", sa.String(length=32), nullable=True),
        sa.Column("address_text", sa.Text(), nullable=True),
        sa.Column("posted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("miss_count", sa.Integer(), nullable=False),
        sa.Column("source_removed", sa.Boolean(), nullable=False),
        sa.Column("removed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("owner_marker", sa.Boolean(), nullable=False),
        sa.Column("agent_marker", sa.Boolean(), nullable=False),
        sa.Column("parse_confidence", sa.Float(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["property_id"], ["properties.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["raw_listing_id"], ["raw_listings.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("raw_listing_id"),
    )
    op.create_index(
        "ix_listings_attr_key",
        "listings",
        ["district", "rooms", "floor", "total_floors"],
        unique=False,
    )
    op.create_index(op.f("ix_listings_property_id"), "listings", ["property_id"], unique=False)
    op.create_table(
        "property_status_events",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("property_id", sa.UUID(), nullable=False),
        sa.Column("from_status", sa.String(length=16), nullable=True),
        sa.Column("to_status", sa.String(length=16), nullable=False),
        sa.Column("actor_type", sa.String(length=16), nullable=False),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["property_id"], ["properties.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_property_status_events_property_id"),
        "property_status_events",
        ["property_id"],
        unique=False,
    )
    op.create_table(
        "dedupe_reviews",
        sa.Column("listing_id", sa.UUID(), nullable=False),
        sa.Column("candidate_property_id", sa.UUID(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("breakdown", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("decision", sa.String(length=16), nullable=True),
        sa.Column("decided_by", sa.UUID(), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["candidate_property_id"], ["properties.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["listing_id"], ["listings.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_dedupe_reviews_candidate_property_id"),
        "dedupe_reviews",
        ["candidate_property_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_dedupe_reviews_listing_id"), "dedupe_reviews", ["listing_id"], unique=False
    )
    op.create_table(
        "listing_contacts",
        sa.Column("listing_id", sa.UUID(), nullable=False),
        sa.Column("contact_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["contact_id"], ["contacts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["listing_id"], ["listings.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("listing_id", "contact_id"),
    )
    op.create_table(
        "listing_photos",
        sa.Column("listing_id", sa.UUID(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("storage_key", sa.Text(), nullable=True),
        sa.Column("sha256", sa.String(length=64), nullable=True),
        sa.Column("phash", sa.BigInteger(), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("download_error", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["listing_id"], ["listings.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_listing_photos_listing_id"), "listing_photos", ["listing_id"], unique=False
    )
    op.create_index(op.f("ix_listing_photos_phash"), "listing_photos", ["phash"], unique=False)
    # ### end Alembic commands ###

    # append-only status events (§7)
    op.execute(
        """
        CREATE OR REPLACE FUNCTION forbid_change() RETURNS trigger AS $$
        BEGIN RAISE EXCEPTION 'property_status_events is append-only'; END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        "CREATE TRIGGER property_status_events_append_only BEFORE UPDATE OR DELETE "
        "ON property_status_events FOR EACH ROW EXECUTE FUNCTION forbid_change()"
    )
    # pHash top-16-bit bucket for blocking (§5.1); phash is a signed bigint
    op.execute(
        "CREATE INDEX ix_listing_photos_bucket ON listing_photos "
        "(((phash >> 48) & 65535)) WHERE phash IS NOT NULL"
    )
    # trigram index for description similarity (§5.2)
    op.execute(
        "CREATE INDEX ix_listings_description_trgm ON listings USING gin (description gin_trgm_ops)"
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP INDEX IF EXISTS ix_listings_description_trgm")
    op.execute("DROP INDEX IF EXISTS ix_listing_photos_bucket")
    op.execute(
        "DROP TRIGGER IF EXISTS property_status_events_append_only ON property_status_events"
    )
    op.execute("DROP FUNCTION IF EXISTS forbid_change")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_listing_photos_phash"), table_name="listing_photos")
    op.drop_index(op.f("ix_listing_photos_listing_id"), table_name="listing_photos")
    op.drop_table("listing_photos")
    op.drop_table("listing_contacts")
    op.drop_index(op.f("ix_dedupe_reviews_listing_id"), table_name="dedupe_reviews")
    op.drop_index(op.f("ix_dedupe_reviews_candidate_property_id"), table_name="dedupe_reviews")
    op.drop_table("dedupe_reviews")
    op.drop_index(
        op.f("ix_property_status_events_property_id"), table_name="property_status_events"
    )
    op.drop_table("property_status_events")
    op.drop_index(op.f("ix_listings_property_id"), table_name="listings")
    op.drop_index("ix_listings_attr_key", table_name="listings")
    op.drop_table("listings")
    op.drop_table("raw_listings")
    op.drop_index("ix_properties_search", table_name="properties", postgresql_using="gin")
    op.drop_index(op.f("ix_properties_district"), table_name="properties")
    op.drop_table("properties")
    op.drop_index(op.f("ix_crawl_runs_source_id"), table_name="crawl_runs")
    op.drop_table("crawl_runs")
    op.drop_table("worker_heartbeat")
    op.drop_table("users")
    op.drop_table("sources")
    op.drop_table("fx_rates")
    op.drop_table("contacts")
    # ### end Alembic commands ###
