/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Bot Monitor */
        get: operations["get_bot_monitor_api_v1_bot_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bot/{message_id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve Bot Message */
        post: operations["resolve_bot_message_api_v1_bot__message_id__resolve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dashboard */
        get: operations["get_dashboard_api_v1_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/duplicates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Duplicates */
        get: operations["list_duplicates_api_v1_duplicates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/duplicates/{review_id}/decide": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Decide Duplicate */
        post: operations["decide_duplicate_api_v1_duplicates__review_id__decide_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_api_v1_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/listings/manual": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Listing By Url */
        post: operations["add_listing_by_url_api_v1_listings_manual_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/listings/manual/form": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Listing By Form */
        post: operations["add_listing_by_form_api_v1_listings_manual_form_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Meta */
        get: operations["meta_api_v1_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/properties": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Properties Endpoint */
        get: operations["list_properties_endpoint_api_v1_properties_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/properties/pins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Property Pins */
        get: operations["property_pins_api_v1_properties_pins_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/properties/{property_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Property Detail */
        get: operations["property_detail_api_v1_properties__property_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/properties/{property_id}/call-log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Call Log */
        post: operations["create_call_log_api_v1_properties__property_id__call_log_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/properties/{property_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Property Status */
        post: operations["set_property_status_api_v1_properties__property_id__status_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Queue */
        get: operations["get_queue_api_v1_queue_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/queue/{property_id}/release": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Release Queue Item */
        post: operations["release_queue_item_api_v1_queue__property_id__release_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/queue/{property_id}/take": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Take Queue Item */
        post: operations["take_queue_item_api_v1_queue__property_id__take_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sources */
        get: operations["list_sources_api_v1_sources_get"];
        put?: never;
        /** Create Source */
        post: operations["create_source_api_v1_sources_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources/{source_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Source */
        patch: operations["patch_source_api_v1_sources__source_id__patch"];
        trace?: never;
    };
    "/api/v1/sources/{source_id}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Source Now
         * @description Queue a source to crawl on the worker's next tick — the manual "fetch now".
         *
         *     The API never crawls synchronously (a full walk takes minutes); it only marks the source
         *     due now and clears any backoff pause, and the running worker picks it up within one tick.
         */
        post: operations["run_source_now_api_v1_sources__source_id__run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources/{source_id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Source Runs */
        get: operations["source_runs_api_v1_sources__source_id__runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users Endpoint */
        get: operations["list_users_endpoint_api_v1_users_get"];
        put?: never;
        /**
         * Create User Endpoint
         * @description Create a user. Duplicate phone -> 409 `user.exists`; a too-short password or a role
         *     outside {admin, agent} is a 422 from `UserCreateIn` before this body runs. Never returns
         *     the password hash (`AdminUserOut` has no such field).
         */
        post: operations["create_user_endpoint_api_v1_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AdminUserOut
         * @description One user row for the admin Settings screen. Never carries the password hash.
         */
        AdminUserOut: {
            /** Active */
            active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Phone */
            phone: string;
            /**
             * Role
             * @enum {string}
             */
            role: "admin" | "agent";
        };
        /** AgentToday */
        AgentToday: {
            /** Calls */
            calls: number;
            /** Found Vacant */
            found_vacant: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** In Queue */
            in_queue: number;
            /** Name */
            name: string;
            /** Working On */
            working_on: string | null;
        };
        /** AvailabilityOut */
        AvailabilityOut: {
            /**
             * At
             * Format: date-time
             */
            at: string;
            /**
             * Status
             * @enum {string}
             */
            status: "vacant" | "taken" | "unknown";
        };
        /** Body_add_listing_by_form_api_v1_listings_manual_form_post */
        Body_add_listing_by_form_api_v1_listings_manual_form_post: {
            /** Area Sqm */
            area_sqm?: number | null;
            /**
             * Description
             * @default
             */
            description: string;
            /** District */
            district?: string | null;
            /** Floor */
            floor?: number | null;
            /** Phone */
            phone?: string | null;
            /** Photos */
            photos?: string[] | null;
            /** Price Amount Minor */
            price_amount_minor?: number | null;
            /** Price Currency */
            price_currency?: ("USD" | "UZS") | null;
            /** Rooms */
            rooms?: number | null;
            /** Title */
            title: string;
            /** Total Floors */
            total_floors?: number | null;
        };
        /** BotReplies */
        BotReplies: {
            /** Answered */
            answered: number;
            /** Sent */
            sent: number;
            /** Taken */
            taken: number;
            /** Unclear */
            unclear: number;
            /** Vacant */
            vacant: number;
        };
        /** BreakdownItem */
        BreakdownItem: {
            /** Detail */
            detail?: string | null;
            /** Points */
            points: number;
            /**
             * Signal
             * @enum {string}
             */
            signal: "contact" | "photo" | "description" | "rooms_floors" | "area" | "price";
        };
        /** CallConditionsIn */
        CallConditionsIn: {
            /** Deposit Months */
            deposit_months?: number | null;
            /**
             * Family Only
             * @default false
             */
            family_only: boolean;
            /**
             * Foreigners
             * @default false
             */
            foreigners: boolean;
        };
        /** CallLogIn */
        CallLogIn: {
            /**
             * @default {
             *       "family_only": false,
             *       "foreigners": false
             *     }
             */
            conditions: components["schemas"]["CallConditionsIn"];
            next_check?: components["schemas"]["NextCheckIn"] | null;
            /**
             * Note
             * @default
             */
            note: string;
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "still_available" | "taken" | "no_answer" | "call_back" | "realtor_not_owner" | "do_not_contact" | "wrong_number";
        };
        /** ChannelStatOut */
        ChannelStatOut: {
            /**
             * Channel
             * @enum {string}
             */
            channel: "telegram" | "sms";
            /** Enabled */
            enabled: boolean;
            /** Per Day */
            per_day: number | null;
            /** Per Hour */
            per_hour: number | null;
            /** Sent Today */
            sent_today: number;
            /**
             * Status
             * @enum {string}
             */
            status: "not_configured" | "ready";
        };
        /** CheckOut */
        CheckOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Logged At
             * Format: date-time
             */
            logged_at: string;
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "still_available" | "taken" | "no_answer" | "call_back" | "realtor_not_owner" | "do_not_contact" | "wrong_number";
            /**
             * Property Id
             * Format: uuid
             */
            property_id: string;
            /**
             * Resulting Status
             * @enum {string}
             */
            resulting_status: "vacant" | "taken" | "unchanged";
        };
        /** ContactOut */
        ContactOut: {
            /** Agency Score */
            agency_score: number;
            /**
             * Classification
             * @enum {string}
             */
            classification: "owner" | "agent" | "unknown";
            /** Display Name */
            display_name: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Identifier */
            identifier: string;
            /** Kind */
            kind: string;
        };
        /** CrawlRunOut */
        CrawlRunOut: {
            /** Changed */
            changed: number;
            /** Error */
            error: string | null;
            /** Failed */
            failed: number;
            /** Finished At */
            finished_at: string | null;
            /** Found */
            found: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** New */
            new: number;
            /** Removed */
            removed: number;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
        };
        /** DashboardOut */
        DashboardOut: {
            /** Agents */
            agents: components["schemas"]["AgentToday"][];
            /** Auto Distribute */
            auto_distribute: boolean;
            bot_replies: components["schemas"]["BotReplies"];
            new_listings: components["schemas"]["NewListings"];
            /** Recheck Items */
            recheck_items: components["schemas"]["RecheckItem"][];
            /** Recheck Total */
            recheck_total: number;
            status_counts: components["schemas"]["StatusCounts"];
            /** Unassigned */
            unassigned: number;
        };
        /** DecideIn */
        DecideIn: {
            /**
             * Decision
             * @enum {string}
             */
            decision: "merge" | "separate";
        };
        /** DecidedRecentOut */
        DecidedRecentOut: {
            /** Count */
            count: number;
            /** Days */
            days: number;
            /** Merged Pct */
            merged_pct: number;
        };
        /** DuplicateOut */
        DuplicateOut: {
            /**
             * Property Id
             * Format: uuid
             */
            property_id: string;
            /** Score */
            score: number;
        };
        /** DuplicateOwnerOut */
        DuplicateOwnerOut: {
            /**
             * Classification
             * @enum {string}
             */
            classification: "owner" | "agent" | "unknown";
            /** Home Count */
            home_count: number | null;
            /** Phone */
            phone: string | null;
        };
        /** DuplicatePairOut */
        DuplicatePairOut: {
            a: components["schemas"]["DuplicateSideOut"];
            b: components["schemas"]["DuplicateSideOut"];
            /** Breakdown */
            breakdown: components["schemas"]["BreakdownItem"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Decided At */
            decided_at?: string | null;
            /** Decided By */
            decided_by?: string | null;
            /** Decision */
            decision?: ("merge" | "separate") | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Score */
            score: number;
        };
        /** DuplicateQueueOut */
        DuplicateQueueOut: {
            decided_recent: components["schemas"]["DecidedRecentOut"];
            /** Items */
            items: components["schemas"]["DuplicatePairOut"][];
            thresholds: components["schemas"]["ThresholdsOut"];
        };
        /**
         * DuplicateSideOut
         * @description One side of a review pair: a property, rendered through a representative listing.
         */
        DuplicateSideOut: {
            /** Address Text */
            address_text: string | null;
            /** Area Sqm */
            area_sqm: number | null;
            /** Description */
            description: string;
            /** District */
            district: string | null;
            /** External Id */
            external_id: string;
            /**
             * First Seen At
             * Format: date-time
             */
            first_seen_at: string;
            /** Floor */
            floor: number | null;
            owner: components["schemas"]["DuplicateOwnerOut"] | null;
            /** Photos */
            photos: string[];
            /** Posted At */
            posted_at: string | null;
            price: components["schemas"]["PriceOut"];
            /** Property Id */
            property_id: string | null;
            /** Rooms */
            rooms: number | null;
            source: components["schemas"]["SourceRef"];
            /** Title */
            title: string;
            /** Total Floors */
            total_floors: number | null;
            /** Url */
            url: string | null;
        };
        /** FxOut */
        FxOut: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /**
             * Fetched At
             * Format: date-time
             */
            fetched_at: string;
            /** Stale */
            stale: boolean;
            /** Usd Uzs */
            usd_uzs: string;
        };
        /** LastActivityOut */
        LastActivityOut: {
            /**
             * At
             * Format: date-time
             */
            at: string;
            /** Text */
            text: string;
        };
        /** ListingOut */
        ListingOut: {
            /** Address Text */
            address_text: string | null;
            /** Agent Marker */
            agent_marker: boolean;
            /** Area Sqm */
            area_sqm: number | null;
            /** Attributes */
            attributes: {
                [key: string]: unknown;
            };
            /** Building Type */
            building_type: string | null;
            /** Contacts */
            contacts: components["schemas"]["ContactOut"][];
            /** Description */
            description: string;
            /** District */
            district: string | null;
            /** External Id */
            external_id: string;
            /**
             * First Seen At
             * Format: date-time
             */
            first_seen_at: string;
            /** Floor */
            floor: number | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Furnished */
            is_furnished: boolean | null;
            /**
             * Last Seen At
             * Format: date-time
             */
            last_seen_at: string;
            /** Latitude */
            latitude: number | null;
            /** Location Label */
            location_label: string | null;
            /** Location Precise */
            location_precise: boolean | null;
            /** Location Radius M */
            location_radius_m: number | null;
            /** Longitude */
            longitude: number | null;
            /** Owner Marker */
            owner_marker: boolean;
            /** Parse Confidence */
            parse_confidence: number;
            /** Photos */
            photos: components["schemas"]["PhotoOut"][];
            /** Posted At */
            posted_at: string | null;
            price: components["schemas"]["PriceOut"];
            /** Renovation */
            renovation: string | null;
            /** Rooms */
            rooms: number | null;
            source: components["schemas"]["SourceRef"];
            /** Source Removed */
            source_removed: boolean;
            /** Title */
            title: string;
            /** Total Floors */
            total_floors: number | null;
            /** Url */
            url: string | null;
            /** Year Built */
            year_built: number | null;
        };
        /** LoginIn */
        LoginIn: {
            /** Password */
            password: string;
            /** Phone */
            phone: string;
        };
        /** ManualResult */
        ManualResult: {
            /** Created */
            created: boolean;
            /** Decision */
            decision: string;
            /**
             * Listing Id
             * Format: uuid
             */
            listing_id: string;
            /**
             * Property Id
             * Format: uuid
             */
            property_id: string;
        };
        /** ManualUrlIn */
        ManualUrlIn: {
            /** Url */
            url: string;
        };
        /** MetaOut */
        MetaOut: {
            /** Contact Classifications */
            contact_classifications: ("owner" | "agent" | "unknown")[];
            /** Districts */
            districts: string[];
            fx: components["schemas"]["FxOut"] | null;
            rules: components["schemas"]["RulesOut"];
            /** Source Kinds */
            source_kinds: ("olx" | "telegram" | "manual")[];
            /** Statuses */
            statuses: ("new" | "active" | "inactive")[];
        };
        /** NewListings */
        NewListings: {
            /** Duplicates */
            duplicates: number;
            /** Manual */
            manual: number;
            /** Olx */
            olx: number;
            /** Telegram */
            telegram: number;
            /** Total */
            total: number;
        };
        /** NextCheckIn */
        NextCheckIn: {
            /**
             * Choice
             * @enum {string}
             */
            choice: "in_3_days" | "tomorrow" | "date";
            /** Date */
            date?: string | null;
        };
        /** OutreachCountersOut */
        OutreachCountersOut: {
            /** Answered */
            answered: number;
            /** Errors */
            errors: number;
            /** Queued */
            queued: number;
            /** Today */
            today: number;
            /** Unclear */
            unclear: number;
        };
        /** OutreachItemOut */
        OutreachItemOut: {
            /**
             * Channel
             * @enum {string}
             */
            channel: "telegram" | "sms";
            /** District */
            district: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Phone */
            phone: string | null;
            /** Price Usd */
            price_usd: number | null;
            /**
             * Property Id
             * Format: uuid
             */
            property_id: string;
            /** Reply At */
            reply_at: string | null;
            /** Reply Text */
            reply_text: string | null;
            /** Result */
            result: ("vacant" | "taken" | "unclear") | null;
            /** Rooms */
            rooms: number | null;
            /** Sent At */
            sent_at: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "sent" | "answered" | "no_reply" | "error";
        };
        /** OutreachMonitorOut */
        OutreachMonitorOut: {
            /** Channels */
            channels: components["schemas"]["ChannelStatOut"][];
            counters: components["schemas"]["OutreachCountersOut"];
            /** Items */
            items: components["schemas"]["OutreachItemOut"][];
        };
        /** OwnerOut */
        OwnerOut: {
            /** Agency Score */
            agency_score: number;
            /**
             * Classification
             * @enum {string}
             */
            classification: "owner" | "agent" | "unknown";
            /** Confidence */
            confidence: number | null;
            /**
             * Contact Id
             * Format: uuid
             */
            contact_id: string;
            /** Display Name */
            display_name: string | null;
            /** Identifier */
            identifier: string;
            /** Kind */
            kind: string;
        };
        /** PhotoOut */
        PhotoOut: {
            /** Height */
            height: number | null;
            /** Position */
            position: number;
            /** Url */
            url: string;
            /** Width */
            width: number | null;
        };
        /** PinOut */
        PinOut: {
            /** Area Sqm */
            area_sqm: number | null;
            /** District */
            district: string | null;
            /** Floor */
            floor: number | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Latitude */
            latitude: number;
            /** Location Label */
            location_label: string | null;
            /** Longitude */
            longitude: number;
            /** Photo Url */
            photo_url: string | null;
            /** Price Usd Min Minor */
            price_usd_min_minor: number | null;
            /** Rooms */
            rooms: number | null;
            /** Source Removed */
            source_removed: boolean;
            /**
             * Status
             * @enum {string}
             */
            status: "new" | "active" | "inactive";
            /** Total Floors */
            total_floors: number | null;
        };
        /** PriceOut */
        PriceOut: {
            /** Amount Minor */
            amount_minor: number | null;
            /** Currency */
            currency: string | null;
            /** Usd Minor */
            usd_minor: number | null;
        };
        /**
         * Problem
         * @description The body of every error response, sent as `application/problem+json`.
         */
        Problem: {
            /**
             * Code
             * @description The machine-readable error code the web translates. One of:
             *     `auth.missing_token`, `auth.token_expired`, `auth.token_invalid`, `auth.user_inactive`,
             *     `auth.invalid_credentials`, `auth.forbidden`, `not_found`, `method_not_allowed`,
             *     `validation_error`, `internal_error`, `listing.unsupported_url`, `listing.invalid_url`,
             *     `listing.gone`, `source.misconfigured`, `source.unavailable`, `source.login_required`,
             *     `source.peer_unresolved`, `source.exists`, `source.disabled`, `user.exists`, `queue.locked`,
             *     `dedupe.already_decided`, `outreach.not_resolvable`; any other HTTP status raised by the
             *     framework becomes `http.<status>`.
             */
            code: string;
            /** Detail */
            detail: string;
            /** Status */
            status: number;
            /** Title */
            title: string;
            /**
             * Type
             * @default about:blank
             */
            type: string;
        };
        /** PropertyDetail */
        PropertyDetail: {
            /** Area Sqm */
            area_sqm: number | null;
            /** Building Type */
            building_type: string | null;
            /** District */
            district: string | null;
            /** Duplicates */
            duplicates: components["schemas"]["DuplicateOut"][];
            /**
             * First Seen At
             * Format: date-time
             */
            first_seen_at: string;
            /** Floor */
            floor: number | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Furnished */
            is_furnished: boolean | null;
            /**
             * Last Seen At
             * Format: date-time
             */
            last_seen_at: string;
            last_status_event: components["schemas"]["StatusEventOut"] | null;
            /** Latitude */
            latitude: number | null;
            /** Listing Count */
            listing_count: number;
            /** Listings */
            listings: components["schemas"]["ListingOut"][];
            /** Location Label */
            location_label: string | null;
            /** Location Radius M */
            location_radius_m: number | null;
            /** Longitude */
            longitude: number | null;
            /** Needs Recheck */
            needs_recheck: boolean;
            /** Photo Url */
            photo_url: string | null;
            /** Price Usd Min Minor */
            price_usd_min_minor: number | null;
            probable_owner: components["schemas"]["OwnerOut"] | null;
            /** Renovation */
            renovation: string | null;
            /** Rooms */
            rooms: number | null;
            /** Source Kinds */
            source_kinds: string[];
            /** Source Removed */
            source_removed: boolean;
            /**
             * Status
             * @enum {string}
             */
            status: "new" | "active" | "inactive";
            /** Status Events */
            status_events: components["schemas"]["StatusEventOut"][];
            /** Total Floors */
            total_floors: number | null;
            /** Year Built */
            year_built: number | null;
        };
        /** PropertyPage */
        PropertyPage: {
            /** Items */
            items: components["schemas"]["PropertyRow"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /** PropertyRow */
        PropertyRow: {
            /** Area Sqm */
            area_sqm: number | null;
            /** Building Type */
            building_type: string | null;
            /** District */
            district: string | null;
            /**
             * First Seen At
             * Format: date-time
             */
            first_seen_at: string;
            /** Floor */
            floor: number | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Furnished */
            is_furnished: boolean | null;
            /**
             * Last Seen At
             * Format: date-time
             */
            last_seen_at: string;
            last_status_event: components["schemas"]["StatusEventOut"] | null;
            /** Latitude */
            latitude: number | null;
            /** Listing Count */
            listing_count: number;
            /** Location Label */
            location_label: string | null;
            /** Location Radius M */
            location_radius_m: number | null;
            /** Longitude */
            longitude: number | null;
            /** Needs Recheck */
            needs_recheck: boolean;
            /** Photo Url */
            photo_url: string | null;
            /** Price Usd Min Minor */
            price_usd_min_minor: number | null;
            probable_owner: components["schemas"]["OwnerOut"] | null;
            /** Renovation */
            renovation: string | null;
            /** Rooms */
            rooms: number | null;
            /** Source Kinds */
            source_kinds: string[];
            /** Source Removed */
            source_removed: boolean;
            /**
             * Status
             * @enum {string}
             */
            status: "new" | "active" | "inactive";
            /** Total Floors */
            total_floors: number | null;
            /** Year Built */
            year_built: number | null;
        };
        /** QueueItemOut */
        QueueItemOut: {
            /** Area Sqm */
            area_sqm: number | null;
            availability: components["schemas"]["AvailabilityOut"];
            /** District */
            district: string | null;
            /** Floor */
            floor: number | null;
            /** Id */
            id: string;
            last_activity: components["schemas"]["LastActivityOut"];
            owner: components["schemas"]["QueueOwnerOut"];
            /** Price Usd */
            price_usd: number;
            /**
             * Property Id
             * Format: uuid
             */
            property_id: string;
            /** Rooms */
            rooms: number | null;
            /**
             * Source
             * @enum {string}
             */
            source: "olx" | "telegram" | "manual";
            state: components["schemas"]["QueueStateOut"];
            /** Sub Area */
            sub_area: string;
            /** Total Floors */
            total_floors: number | null;
        };
        /** QueueOwnerOut */
        QueueOwnerOut: {
            /**
             * Classification
             * @enum {string}
             */
            classification: "owner" | "agent" | "unknown";
            /** Home Count */
            home_count: number | null;
            /** Phone */
            phone: string;
        };
        /** QueueStateOut */
        QueueStateOut: {
            /** Agent Name */
            agent_name?: string | null;
            /**
             * Kind
             * @enum {string}
             */
            kind: "mine" | "locked" | "new" | "retry";
            /** Until */
            until?: string | null;
        };
        /** RecheckItem */
        RecheckItem: {
            /** Agent */
            agent: string | null;
            /** District */
            district: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Last Checked At
             * Format: date-time
             */
            last_checked_at: string;
            /** Price Usd */
            price_usd: number | null;
            /** Rooms */
            rooms: number | null;
            /** Source Removed */
            source_removed: boolean;
        };
        /** RefreshIn */
        RefreshIn: {
            /** Refresh */
            refresh: string;
        };
        /** ResolveIn */
        ResolveIn: {
            /**
             * Result
             * @enum {string}
             */
            result: "vacant" | "taken";
        };
        /**
         * RulesOut
         * @description Only the config constants the system actually enforces, each read from its real source
         *     (not a literal here). Quiet-hours and per-contact send caps are deliberately absent: they
         *     are NOT implemented, so advertising them would imply a guarantee the backend does not make.
         */
        RulesOut: {
            /** Duplicate Merge Threshold */
            duplicate_merge_threshold: number;
            /** Lock Hours */
            lock_hours: number;
            /** New Listing Check Days */
            new_listing_check_days: number;
            /** Recheck Days */
            recheck_days: number;
            /** Sms Per Day */
            sms_per_day: number | null;
            /** Telegram Per Day */
            telegram_per_day: number | null;
            /** Telegram Per Hour */
            telegram_per_hour: number | null;
        };
        /** SourceCreateIn */
        SourceCreateIn: {
            /**
             * Interval Seconds
             * @default 900
             */
            interval_seconds: number;
            /**
             * Kind
             * @default telegram
             * @constant
             */
            kind: "telegram";
            /** Name */
            name?: string | null;
            /** Peer */
            peer: string;
        };
        /** SourceOut */
        SourceOut: {
            /** Config */
            config: {
                [key: string]: unknown;
            };
            /** Consecutive Failures */
            consecutive_failures: number;
            /** Enabled */
            enabled: boolean;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Interval Seconds */
            interval_seconds: number;
            /**
             * Kind
             * @enum {string}
             */
            kind: "olx" | "telegram" | "manual";
            last_run: components["schemas"]["CrawlRunOut"] | null;
            /** Last Run At */
            last_run_at: string | null;
            /** Name */
            name: string;
            /** Next Run At */
            next_run_at: string | null;
            /** Paused Until */
            paused_until: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "failing" | "login_required" | "paused" | "misconfigured";
        };
        /** SourcePatchIn */
        SourcePatchIn: {
            /** Enabled */
            enabled: boolean;
        };
        /** SourceRef */
        SourceRef: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "olx" | "telegram" | "manual";
            /** Name */
            name: string;
        };
        /** SourcesOut */
        SourcesOut: {
            fx: components["schemas"]["FxOut"] | null;
            /** Items */
            items: components["schemas"]["SourceOut"][];
        };
        /** StatusCounts */
        StatusCounts: {
            /** New */
            new: number;
            /** Taken */
            taken: number;
            /** To Check Today */
            to_check_today: number;
            /** Vacant */
            vacant: number;
            /** Vacant Confirmed 3D */
            vacant_confirmed_3d: number;
        };
        /** StatusEventOut */
        StatusEventOut: {
            /** Actor Id */
            actor_id: string | null;
            /** Actor Type */
            actor_type: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** From Status */
            from_status: string | null;
            /** Id */
            id: number;
            /** Note */
            note: string | null;
            /** To Status */
            to_status: string;
        };
        /** StatusIn */
        StatusIn: {
            /** Note */
            note?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "inactive";
        };
        /** ThresholdsOut */
        ThresholdsOut: {
            /** Merge Threshold */
            merge_threshold: number;
            /** Review Threshold */
            review_threshold: number;
        };
        /** TokenPair */
        TokenPair: {
            /** Access */
            access: string;
            /** Refresh */
            refresh: string;
            /**
             * Token Type
             * @default bearer
             * @constant
             */
            token_type: "bearer";
        };
        /**
         * UserCreateIn
         * @description Admin Settings "add user" form. `role` is a closed set and `password` a minimum
         *     length, both enforced here so a bad request is a 422 before the service is called.
         */
        UserCreateIn: {
            /** Name */
            name: string;
            /** Password */
            password: string;
            /** Phone */
            phone: string;
            /**
             * Role
             * @enum {string}
             */
            role: "admin" | "agent";
        };
        /** UserOut */
        UserOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Locale */
            locale: string;
            /** Name */
            name: string;
            /** Phone */
            phone: string;
            /** Role */
            role: string;
        };
        /** ValidationIssue */
        ValidationIssue: {
            /** Loc */
            loc: string[];
            /** Msg */
            msg: string;
            /** Type */
            type: string;
        };
        /** ValidationProblem */
        ValidationProblem: {
            /**
             * Code
             * @description The machine-readable error code the web translates. One of:
             *     `auth.missing_token`, `auth.token_expired`, `auth.token_invalid`, `auth.user_inactive`,
             *     `auth.invalid_credentials`, `auth.forbidden`, `not_found`, `method_not_allowed`,
             *     `validation_error`, `internal_error`, `listing.unsupported_url`, `listing.invalid_url`,
             *     `listing.gone`, `source.misconfigured`, `source.unavailable`, `source.login_required`,
             *     `source.peer_unresolved`, `source.exists`, `source.disabled`, `user.exists`, `queue.locked`,
             *     `dedupe.already_decided`, `outreach.not_resolvable`; any other HTTP status raised by the
             *     framework becomes `http.<status>`.
             */
            code: string;
            /** Detail */
            detail: string;
            /** Errors */
            errors: components["schemas"]["ValidationIssue"][];
            /** Status */
            status: number;
            /** Title */
            title: string;
            /**
             * Type
             * @default about:blank
             */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description wrong phone or password */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationProblem"];
                };
            };
            /** @description unexpected error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    refresh_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description invalid or expired refresh token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationProblem"];
                };
            };
            /** @description unexpected error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    get_bot_monitor_api_v1_bot_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutreachMonitorOut"];
                };
            };
            /** @description missing, invalid or expired token; or inactive user */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description unexpected error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    resolve_bot_message_api_v1_bot__message_id__resolve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                message_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutreachItemOut"];
                };
            };
            /** @description missing, invalid or expired token; or inactive user */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description unknown outreach message */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description message is not awaiting manual classification */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationProblem"];
                };
            };
            /** @description unexpected error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    get_dashboard_api_v1_dashboard_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardOut"];
                };
            };
            /** @description missing, invalid or expired token; or inactive user */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description unexpected error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    list_duplicates_api_v1_duplicates_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DuplicateQueueOut"];
                };
            };
            /** @description missing, invalid or expired token; or inactive user */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description unexpected error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    decide_duplicate_api_v1_duplicates__review_id__decide_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                review_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecideIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DuplicatePairOut"];
                };
            };
            /** @description missing, invalid or expired token; or inactive user */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description unknown review */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description this review has already been decided */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationProblem"];
                };
            };
            /** @description unexpected error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    healthz_api_v1_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description unexpected error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description database unreachable or worker stale */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    add_listing_by_url_api_v1_listings_manual_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManualUrlIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManualResult"];
                };
            };
            /** @description missing, invalid or expired token; or inactive user */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description the listing no longer exists at the source */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationProblem"];
                };
            };
            /** @description unexpected error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description the source is unavailable, blocked or misconfigured */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    add_listing_by_form_api_v1_listings_manual_form_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_add_listing_by_form_api_v1_listings_manual_form_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManualResult"];
                };
            };
            /** @description missing, invalid or expired token; or inactive user */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationProblem"];
                };
            };
            /** @description unexpected error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    me_api_v1_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description missing, invalid or expired token; or inactive user */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description unexpected error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    meta_api_v1_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetaOut"];
                };
            };
            /** @description missing, invalid or expired token; or inactive user */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description unexpected error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    list_properties_endpoint_api_v1_properties_get: {
        parameters: {
            query?: {
                district?: string[] | null;
                rooms?: number[] | null;
                /** @description whole USD */
                price_min?: number | null;
                /** @description whole USD */
                price_max?: number | null;
                status?: ("new" | "active" | "inactive")[] | null;
                source?: ("olx" | "telegram" | "manual") | null;
                owner_only?: boolean;
                /** @description include properties removed at the source */
                removed?: boolean;
                area_min?: number | null;
                area_max?: number | null;
                floor_min?: number | null;
                floor_max?: number | null;
                not_first_floor?: boolean;
                not_top_floor?: boolean;
                building_type?: string[] | null;
                furnished?: boolean | null;
                renovation?: string[] | null;
                posted_within?: ("24h" | "3d" | "7d") | null;
                has_photos?: boolean;
                min_lat?: number | null;
                min_lon?: number | null;
                max_lat?: number | null;
                max_lon?: number | null;
                q?: string | null;
                sort?: "last_seen" | "first_seen" | "price_asc" | "price_desc";
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyPage"];
                };
            };
            /** @description missing, invalid or expired token; or inactive user */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationProblem"];
                };
            };
            /** @description unexpected error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    property_pins_api_v1_properties_pins_get: {
        parameters: {
            query?: {
                district?: string[] | null;
                rooms?: number[] | null;
                price_min?: number | null;
                price_max?: number | null;
                status?: ("new" | "active" | "inactive")[] | null;
                source?: ("olx" | "telegram" | "manual") | null;
                owner_only?: boolean;
                removed?: boolean;
                q?: string | null;
                area_min?: number | null;
                area_max?: number | null;
                floor_min?: number | null;
                floor_max?: number | null;
                not_first_floor?: boolean;
                not_top_floor?: boolean;
                building_type?: string[] | null;
                furnished?: boolean | null;
                renovation?: string[] | null;
                posted_within?: ("24h" | "3d" | "7d") | null;
                has_photos?: boolean;
                min_lat?: number | null;
                min_lon?: number | null;
                max_lat?: number | null;
                max_lon?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PinOut"][];
                };
            };
            /** @description missing, invalid or expired token; or inactive user */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationProblem"];
                };
            };
            /** @description unexpected error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    property_detail_api_v1_properties__property_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                property_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyDetail"];
                };
            };
            /** @description missing, invalid or expired token; or inactive user */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description unknown property */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationProblem"];
                };
            };
            /** @description unexpected error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    create_call_log_api_v1_properties__property_id__call_log_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                property_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CallLogIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckOut"];
                };
            };
            /** @description missing, invalid or expired token; or inactive user */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description unknown property */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationProblem"];
                };
            };
            /** @description unexpected error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    set_property_status_api_v1_properties__property_id__status_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                property_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatusIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusEventOut"];
                };
            };
            /** @description missing, invalid or expired token; or inactive user */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description unknown property */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationProblem"];
                };
            };
            /** @description unexpected error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    get_queue_api_v1_queue_get: {
        parameters: {
            query?: {
                scope?: "all" | "today" | "retry";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueItemOut"][];
                };
            };
            /** @description missing, invalid or expired token; or inactive user */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationProblem"];
                };
            };
            /** @description unexpected error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    release_queue_item_api_v1_queue__property_id__release_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                property_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description missing, invalid or expired token; or inactive user */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description unknown property */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationProblem"];
                };
            };
            /** @description unexpected error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    take_queue_item_api_v1_queue__property_id__take_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                property_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueItemOut"];
                };
            };
            /** @description missing, invalid or expired token; or inactive user */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description unknown property */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description another agent holds this property */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationProblem"];
                };
            };
            /** @description unexpected error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    list_sources_api_v1_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourcesOut"];
                };
            };
            /** @description missing, invalid or expired token; or inactive user */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description admin role required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description unexpected error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    create_source_api_v1_sources_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceCreateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceOut"];
                };
            };
            /** @description missing, invalid or expired token; or inactive user */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description admin role required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description name taken */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationProblem"];
                };
            };
            /** @description unexpected error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description telegram unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    patch_source_api_v1_sources__source_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourcePatchIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceOut"];
                };
            };
            /** @description missing, invalid or expired token; or inactive user */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description admin role required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description unknown source */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationProblem"];
                };
            };
            /** @description unexpected error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    run_source_now_api_v1_sources__source_id__run_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceOut"];
                };
            };
            /** @description missing, invalid or expired token; or inactive user */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description admin role required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description unknown source */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description source disabled */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationProblem"];
                };
            };
            /** @description unexpected error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    source_runs_api_v1_sources__source_id__runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CrawlRunOut"][];
                };
            };
            /** @description missing, invalid or expired token; or inactive user */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description admin role required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description unknown source */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationProblem"];
                };
            };
            /** @description unexpected error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    list_users_endpoint_api_v1_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserOut"][];
                };
            };
            /** @description missing, invalid or expired token; or inactive user */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description admin role required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description unexpected error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    create_user_endpoint_api_v1_users_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserOut"];
                };
            };
            /** @description missing, invalid or expired token; or inactive user */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description admin role required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description phone already registered */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationProblem"];
                };
            };
            /** @description unexpected error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
}
