/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_api_v1_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/listings/manual": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Listing By Url */
        post: operations["add_listing_by_url_api_v1_listings_manual_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/listings/manual/form": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Listing By Form */
        post: operations["add_listing_by_form_api_v1_listings_manual_form_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Meta */
        get: operations["meta_api_v1_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/properties": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Properties Endpoint */
        get: operations["list_properties_endpoint_api_v1_properties_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/properties/{property_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Property Detail */
        get: operations["property_detail_api_v1_properties__property_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/properties/{property_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Property Status */
        post: operations["set_property_status_api_v1_properties__property_id__status_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sources */
        get: operations["list_sources_api_v1_sources_get"];
        put?: never;
        /** Create Source */
        post: operations["create_source_api_v1_sources_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources/{source_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Source */
        patch: operations["patch_source_api_v1_sources__source_id__patch"];
        trace?: never;
    };
    "/api/v1/sources/{source_id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Source Runs */
        get: operations["source_runs_api_v1_sources__source_id__runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_add_listing_by_form_api_v1_listings_manual_form_post */
        Body_add_listing_by_form_api_v1_listings_manual_form_post: {
            /** Area Sqm */
            area_sqm?: number | null;
            /**
             * Description
             * @default
             */
            description: string;
            /** District */
            district?: string | null;
            /** Floor */
            floor?: number | null;
            /** Phone */
            phone?: string | null;
            /** Photos */
            photos?: string[] | null;
            /** Price Amount Minor */
            price_amount_minor?: number | null;
            /** Price Currency */
            price_currency?: ("USD" | "UZS") | null;
            /** Rooms */
            rooms?: number | null;
            /** Title */
            title: string;
            /** Total Floors */
            total_floors?: number | null;
        };
        /** ContactOut */
        ContactOut: {
            /** Agency Score */
            agency_score: number;
            /**
             * Classification
             * @enum {string}
             */
            classification: "owner" | "agent" | "unknown";
            /** Display Name */
            display_name: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Identifier */
            identifier: string;
            /** Kind */
            kind: string;
        };
        /** CrawlRunOut */
        CrawlRunOut: {
            /** Changed */
            changed: number;
            /** Error */
            error: string | null;
            /** Failed */
            failed: number;
            /** Finished At */
            finished_at: string | null;
            /** Found */
            found: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** New */
            new: number;
            /** Removed */
            removed: number;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
        };
        /** DuplicateOut */
        DuplicateOut: {
            /**
             * Property Id
             * Format: uuid
             */
            property_id: string;
            /** Score */
            score: number;
        };
        /** FxOut */
        FxOut: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /**
             * Fetched At
             * Format: date-time
             */
            fetched_at: string;
            /** Stale */
            stale: boolean;
            /** Usd Uzs */
            usd_uzs: string;
        };
        /** ListingOut */
        ListingOut: {
            /** Address Text */
            address_text: string | null;
            /** Agent Marker */
            agent_marker: boolean;
            /** Area Sqm */
            area_sqm: number | null;
            /** Contacts */
            contacts: components["schemas"]["ContactOut"][];
            /** Description */
            description: string;
            /** District */
            district: string | null;
            /** External Id */
            external_id: string;
            /**
             * First Seen At
             * Format: date-time
             */
            first_seen_at: string;
            /** Floor */
            floor: number | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Last Seen At
             * Format: date-time
             */
            last_seen_at: string;
            /** Owner Marker */
            owner_marker: boolean;
            /** Parse Confidence */
            parse_confidence: number;
            /** Photos */
            photos: components["schemas"]["PhotoOut"][];
            /** Posted At */
            posted_at: string | null;
            price: components["schemas"]["PriceOut"];
            /** Rooms */
            rooms: number | null;
            source: components["schemas"]["SourceRef"];
            /** Source Removed */
            source_removed: boolean;
            /** Title */
            title: string;
            /** Total Floors */
            total_floors: number | null;
            /** Url */
            url: string | null;
        };
        /** LoginIn */
        LoginIn: {
            /** Password */
            password: string;
            /** Phone */
            phone: string;
        };
        /** ManualResult */
        ManualResult: {
            /** Created */
            created: boolean;
            /** Decision */
            decision: string;
            /**
             * Listing Id
             * Format: uuid
             */
            listing_id: string;
            /**
             * Property Id
             * Format: uuid
             */
            property_id: string;
        };
        /** ManualUrlIn */
        ManualUrlIn: {
            /** Url */
            url: string;
        };
        /** MetaOut */
        MetaOut: {
            /** Contact Classifications */
            contact_classifications: ("owner" | "agent" | "unknown")[];
            /** Districts */
            districts: string[];
            /** Source Kinds */
            source_kinds: ("olx" | "telegram" | "manual")[];
            /** Statuses */
            statuses: ("new" | "active" | "inactive")[];
        };
        /** OwnerOut */
        OwnerOut: {
            /** Agency Score */
            agency_score: number;
            /**
             * Classification
             * @enum {string}
             */
            classification: "owner" | "agent" | "unknown";
            /** Confidence */
            confidence: number | null;
            /**
             * Contact Id
             * Format: uuid
             */
            contact_id: string;
            /** Display Name */
            display_name: string | null;
            /** Identifier */
            identifier: string;
            /** Kind */
            kind: string;
        };
        /** PhotoOut */
        PhotoOut: {
            /** Height */
            height: number | null;
            /** Position */
            position: number;
            /** Url */
            url: string;
            /** Width */
            width: number | null;
        };
        /** PriceOut */
        PriceOut: {
            /** Amount Minor */
            amount_minor: number | null;
            /** Currency */
            currency: string | null;
            /** Usd Minor */
            usd_minor: number | null;
        };
        /**
         * Problem
         * @description The body of every error response, sent as `application/problem+json`.
         */
        Problem: {
            /**
             * Code
             * @description The machine-readable error code the web translates. One of:
             *     `auth.missing_token`, `auth.token_expired`, `auth.token_invalid`, `auth.user_inactive`,
             *     `auth.invalid_credentials`, `auth.forbidden`, `not_found`, `method_not_allowed`,
             *     `validation_error`, `internal_error`, `listing.unsupported_url`, `listing.invalid_url`,
             *     `listing.gone`, `source.misconfigured`, `source.unavailable`, `source.login_required`,
             *     `source.peer_unresolved`, `source.exists`; any other HTTP status raised by the framework
             *     becomes `http.<status>`.
             */
            code: string;
            /** Detail */
            detail: string;
            /** Status */
            status: number;
            /** Title */
            title: string;
            /**
             * Type
             * @default about:blank
             */
            type: string;
        };
        /** PropertyDetail */
        PropertyDetail: {
            /** Area Sqm */
            area_sqm: number | null;
            /** District */
            district: string | null;
            /** Duplicates */
            duplicates: components["schemas"]["DuplicateOut"][];
            /**
             * First Seen At
             * Format: date-time
             */
            first_seen_at: string;
            /** Floor */
            floor: number | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Last Seen At
             * Format: date-time
             */
            last_seen_at: string;
            last_status_event: components["schemas"]["StatusEventOut"] | null;
            /** Listing Count */
            listing_count: number;
            /** Listings */
            listings: components["schemas"]["ListingOut"][];
            /** Needs Recheck */
            needs_recheck: boolean;
            /** Photo Url */
            photo_url: string | null;
            /** Price Usd Min Minor */
            price_usd_min_minor: number | null;
            probable_owner: components["schemas"]["OwnerOut"] | null;
            /** Rooms */
            rooms: number | null;
            /** Source Kinds */
            source_kinds: string[];
            /** Source Removed */
            source_removed: boolean;
            /**
             * Status
             * @enum {string}
             */
            status: "new" | "active" | "inactive";
            /** Status Events */
            status_events: components["schemas"]["StatusEventOut"][];
            /** Total Floors */
            total_floors: number | null;
        };
        /** PropertyPage */
        PropertyPage: {
            /** Items */
            items: components["schemas"]["PropertyRow"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /** PropertyRow */
        PropertyRow: {
            /** Area Sqm */
            area_sqm: number | null;
            /** District */
            district: string | null;
            /**
             * First Seen At
             * Format: date-time
             */
            first_seen_at: string;
            /** Floor */
            floor: number | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Last Seen At
             * Format: date-time
             */
            last_seen_at: string;
            last_status_event: components["schemas"]["StatusEventOut"] | null;
            /** Listing Count */
            listing_count: number;
            /** Needs Recheck */
            needs_recheck: boolean;
            /** Photo Url */
            photo_url: string | null;
            /** Price Usd Min Minor */
            price_usd_min_minor: number | null;
            probable_owner: components["schemas"]["OwnerOut"] | null;
            /** Rooms */
            rooms: number | null;
            /** Source Kinds */
            source_kinds: string[];
            /** Source Removed */
            source_removed: boolean;
            /**
             * Status
             * @enum {string}
             */
            status: "new" | "active" | "inactive";
            /** Total Floors */
            total_floors: number | null;
        };
        /** RefreshIn */
        RefreshIn: {
            /** Refresh */
            refresh: string;
        };
        /** SourceCreateIn */
        SourceCreateIn: {
            /**
             * Interval Seconds
             * @default 900
             */
            interval_seconds: number;
            /**
             * Kind
             * @default telegram
             * @constant
             */
            kind: "telegram";
            /** Name */
            name?: string | null;
            /** Peer */
            peer: string;
        };
        /** SourceOut */
        SourceOut: {
            /** Config */
            config: {
                [key: string]: unknown;
            };
            /** Consecutive Failures */
            consecutive_failures: number;
            /** Enabled */
            enabled: boolean;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Interval Seconds */
            interval_seconds: number;
            /**
             * Kind
             * @enum {string}
             */
            kind: "olx" | "telegram" | "manual";
            last_run: components["schemas"]["CrawlRunOut"] | null;
            /** Last Run At */
            last_run_at: string | null;
            /** Name */
            name: string;
            /** Next Run At */
            next_run_at: string | null;
            /** Paused Until */
            paused_until: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "failing" | "login_required" | "paused" | "misconfigured";
        };
        /** SourcePatchIn */
        SourcePatchIn: {
            /** Enabled */
            enabled: boolean;
        };
        /** SourceRef */
        SourceRef: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "olx" | "telegram" | "manual";
            /** Name */
            name: string;
        };
        /** SourcesOut */
        SourcesOut: {
            fx: components["schemas"]["FxOut"] | null;
            /** Items */
            items: components["schemas"]["SourceOut"][];
        };
        /** StatusEventOut */
        StatusEventOut: {
            /** Actor Id */
            actor_id: string | null;
            /** Actor Type */
            actor_type: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** From Status */
            from_status: string | null;
            /** Id */
            id: number;
            /** Note */
            note: string | null;
            /** To Status */
            to_status: string;
        };
        /** StatusIn */
        StatusIn: {
            /** Note */
            note?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "inactive";
        };
        /** TokenPair */
        TokenPair: {
            /** Access */
            access: string;
            /** Refresh */
            refresh: string;
            /**
             * Token Type
             * @default bearer
             * @constant
             */
            token_type: "bearer";
        };
        /** UserOut */
        UserOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Locale */
            locale: string;
            /** Name */
            name: string;
            /** Phone */
            phone: string;
            /** Role */
            role: string;
        };
        /** ValidationIssue */
        ValidationIssue: {
            /** Loc */
            loc: string[];
            /** Msg */
            msg: string;
            /** Type */
            type: string;
        };
        /** ValidationProblem */
        ValidationProblem: {
            /**
             * Code
             * @description The machine-readable error code the web translates. One of:
             *     `auth.missing_token`, `auth.token_expired`, `auth.token_invalid`, `auth.user_inactive`,
             *     `auth.invalid_credentials`, `auth.forbidden`, `not_found`, `method_not_allowed`,
             *     `validation_error`, `internal_error`, `listing.unsupported_url`, `listing.invalid_url`,
             *     `listing.gone`, `source.misconfigured`, `source.unavailable`, `source.login_required`,
             *     `source.peer_unresolved`, `source.exists`; any other HTTP status raised by the framework
             *     becomes `http.<status>`.
             */
            code: string;
            /** Detail */
            detail: string;
            /** Errors */
            errors: components["schemas"]["ValidationIssue"][];
            /** Status */
            status: number;
            /** Title */
            title: string;
            /**
             * Type
             * @default about:blank
             */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description wrong phone or password */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationProblem"];
                };
            };
            /** @description unexpected error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    refresh_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description invalid or expired refresh token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationProblem"];
                };
            };
            /** @description unexpected error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    healthz_api_v1_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description unexpected error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description database unreachable or worker stale */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    add_listing_by_url_api_v1_listings_manual_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManualUrlIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManualResult"];
                };
            };
            /** @description missing, invalid or expired token; or inactive user */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description the listing no longer exists at the source */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationProblem"];
                };
            };
            /** @description unexpected error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description the source is unavailable, blocked or misconfigured */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    add_listing_by_form_api_v1_listings_manual_form_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_add_listing_by_form_api_v1_listings_manual_form_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManualResult"];
                };
            };
            /** @description missing, invalid or expired token; or inactive user */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationProblem"];
                };
            };
            /** @description unexpected error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    me_api_v1_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description missing, invalid or expired token; or inactive user */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description unexpected error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    meta_api_v1_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetaOut"];
                };
            };
            /** @description missing, invalid or expired token; or inactive user */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description unexpected error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    list_properties_endpoint_api_v1_properties_get: {
        parameters: {
            query?: {
                district?: string[] | null;
                rooms?: number[] | null;
                /** @description whole USD */
                price_min?: number | null;
                /** @description whole USD */
                price_max?: number | null;
                status?: ("new" | "active" | "inactive")[] | null;
                source?: ("olx" | "telegram" | "manual") | null;
                owner_only?: boolean;
                /** @description include properties removed at the source */
                removed?: boolean;
                q?: string | null;
                sort?: "last_seen" | "first_seen" | "price_asc" | "price_desc";
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyPage"];
                };
            };
            /** @description missing, invalid or expired token; or inactive user */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationProblem"];
                };
            };
            /** @description unexpected error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    property_detail_api_v1_properties__property_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                property_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyDetail"];
                };
            };
            /** @description missing, invalid or expired token; or inactive user */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description unknown property */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationProblem"];
                };
            };
            /** @description unexpected error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    set_property_status_api_v1_properties__property_id__status_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                property_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatusIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusEventOut"];
                };
            };
            /** @description missing, invalid or expired token; or inactive user */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description unknown property */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationProblem"];
                };
            };
            /** @description unexpected error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    list_sources_api_v1_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourcesOut"];
                };
            };
            /** @description missing, invalid or expired token; or inactive user */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description admin role required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description unexpected error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    create_source_api_v1_sources_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceCreateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceOut"];
                };
            };
            /** @description missing, invalid or expired token; or inactive user */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description admin role required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description name taken */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationProblem"];
                };
            };
            /** @description unexpected error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description telegram unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    patch_source_api_v1_sources__source_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourcePatchIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceOut"];
                };
            };
            /** @description missing, invalid or expired token; or inactive user */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description admin role required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description unknown source */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationProblem"];
                };
            };
            /** @description unexpected error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    source_runs_api_v1_sources__source_id__runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CrawlRunOut"][];
                };
            };
            /** @description missing, invalid or expired token; or inactive user */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description admin role required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description unknown source */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationProblem"];
                };
            };
            /** @description unexpected error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
}
